version: '3.8'
services:
  server:
    container_name: server
    image: tejodeepmitraroy/salesless-app:v1
    restart: always
    environment:
      # DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/ecom'
      DATABASE_URL: 'postgres://avnadmin:AVNS_qxMMil7dtkMoqb3M83G@pg-19a83f3f-tejodeepmitraroy2002.e.aivencloud.com:18881/defaultdbs'
      REDIS_URL: 'rediss://default:ASS3AAImcDEyMjk1ODIzMzRlNmI0NWYzYTVmZmM0NDZhMDA2Yzg1N3AxOTM5OQ@welcomed-anchovy-9399.upstash.io:6379'

      FRONTEND_ENDPOINT_URL: 'http://localhost:5173'

      OAUTH_CLIENT_ID: '452133296020-gbjbdmhecknjmnuq06psts06i222ose6.apps.googleusercontent.com'
      OAUTH_CLIENT_SECRET: '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'
      OAUTH_TOKEN_URL: 'https://oauth2.googleapis.com/token'
      OAUTH_CALLBACK_URL: 'http://localhost:8000/api/v1/auth/google/callback'

      JWT_SECRET: 'your_jwt_secret'
      ACCESS_TOKEN_SECRET: 'Tejodeep'
      REFRESH_TOKEN_SECRET: 'your_refresh_token_secret'
      VERIFY_EMAIL_TOKEN_SERECT: 'verify Email'
      ACCESS_TOKEN_EXPIRY: '15m'
      REFRESH_TOKEN_EXPIRY: '7d'
      FORGET_PASSWORD_JWT_SECRET: 'forgetPassword'

      REGION: ap-south-1
      S3_BUCKET_NAME: salesless1
      ACCESS_KEY_ID: 'AKIAZAMYYGMFGUFH7W6G'
      SECRET_ACCESS_KEY: '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'

      EMAIL_SERVICE_URI: 'http://localhost:8001/api/v1/emails'
      RAZORPAY_API_KEY: 'rzp_test_GHoEnROzSXtUn9'
      RAZORPAY_API_SECRET: 'PjtV5uoK8KveQXtshbPGgYa1'

      STRIPE_SECRET_KEY: 'sk_test_51Rta7mSEXP17teEvnbrYK0THtHGSPxjxjBVZeV6pER2XhSCHRX6UosEqfcdDCxihL2rmVFAHT5ryK5hcDEEhluYA0075hE8SZr'
      STRIPE_WEBHOOK_SECRET: 'whsec_2a37b945ba3222c523bcb74b86c544bdf6465b40ad37138b2252cf211c946b2b'
    ports:
      - 8181:8000
